name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    name: Running Local Tests
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue

      - name: Upload Tests Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/unit-test'
