name: Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    name: Running Local Tests
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue

      - name: Upload Tests Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports/tests/'

#  android-test-job:
#    name: Android Tests
#    runs-on:  macOS-latest
#    continue-on-error: true
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Validate Gradle Wrapper
#        uses: gradle/wrapper-validation-action@v1
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: 17
#
#      - name: Run Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectAndroidTest
#
#      - name: Upload Android Tests Reports
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: android-test-reports
#          path: '**/build/reports/androidTests/'
